[package]
name = "inss-watcher"
version = "0.1.0"
edition = "2024"

[dependencies]
notify = "8.2.0"
pdf-extract = "0.10.0"
regex = "1.12.2"
log = "0.4.28"
env_logger = "0.11.8"
anyhow = "1.0.100"
dirs = "6.0.0"
